model: clip
model_args:
  clip_model_name: 'openai/clip-vit-base-patch16'
  dropout_rate: 0.1
loss: cross_entropy
loss_args: {}
dataset: meme_hate
dataset_args:
  annotations_file: 'data/annotations.csv'
  tokenizer: null  # Replace with tokenizer instance or path
  max_length: 128
  transform: null
trainer: base
batch_size: 32
epochs: 10
learning_rate: 0.0001 